{
 "title": "DB server monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPULA 1 min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"10.10.1.223:9100\", job=\"debian-metrics\"}"
    }
   ]
  },
  {
   "title": "CPULA 5",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "node_load5{instance=\"10.10.1.223:9100\", job=\"debian-metrics\"}"
    }
   ]
  },
  {
   "title": "CPULA 15",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load15{instance=\"10.10.1.223:9100\", job=\"debian-metrics\"}"
    }
   ]
  },
  {
   "title": "MemFree_bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"10.10.1.223:9100\", job=\"debian-metrics\"}"
    }
   ]
  },
  {
   "title": "filesystem_free_bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/sda1\", fstype=\"ext4\", instance=\"10.10.1.223:9100\", job=\"debian-metrics\", mountpoint=\"/\"}"
    }
   ]
  }
 ]
}