version: '3'
services:

  node-export:
      image: prom/node-exporter:latest
      container_name: node-exporter
      volumes: 
        - ./node-data:/mnt:Z
      ports:
        - 9100:9100
      networks:
        - monit-network

  prometheus:
       image: prom/prometheus:latest
       container_name: prometheus
       privileged: true
       user: root
       volumes:
         - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:Z
       ports:
         - 9090:9090
       networks:
         - monit-network

  grafana:
       image: grafana/grafana:latest
       container_name: grafana
       ports:
         - 3000:3000
       volumes:
          - ./configs/grafana.ini:/etc/grafana/grafana.ini:Z
       networks:
         - monit-network

networks:
  monit-network:
    driver: bridge

